name: Validate PR
on:
  pull_request:
    branches:
      - master
jobs:
  tests-package:
    name: Tests & Package
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: "corretto"
          java-version: "17"
      - name: Checkout OpenERP Atomfeed Service Repo
        uses: actions/checkout@v2
      - name: Run Tests
        run: ./mvnw --no-transfer-progress clean test
      - name: Package
        run: ./mvnw --no-transfer-progress clean package -DskipTests
